# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseEntregable' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseEntregable
  pod 'Firebase'
  pod 'FirebaseUI'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Kingfisher', '~> 4.0'
  pod 'IQKeyboardManagerSwift'
end
